### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by MikaGuraN** [L-JINBIN/AndroidLua#1]
1. getter和setter alua本来就已经实现
2. alua支持.直接访问内部类
3. 建议重写整个结构 只保留原作者的lua调用方式
(也就是新建lua状态机 执行代码 调用函数的方法)
因为原作者的代码充满了 复制的代码。而且他ZipUtil解压时缓存太小 速度特别慢

**Comment by MikaGuraN** [comment]
他的有些代码 到处复制。。。真的没法看 。。还弄出个luacontect xswl

**Comment by MikaGuraN** [comment]
还有: github开源的是旧版了 我这里有新版源码。。

**Comment by MikaGuraN** [comment]
他的ide用lua实现。。
现在被一群小学生拿去改。。
所以现在各种lua ide 全都是抄alua的

**Comment by L-JINBIN** [comment]
我说的的相对于LuaJava的改进，另外MT脚本引擎我已经放弃Lua转用JS，这其中的过程我在论坛里说了https://bbs.binmt.cc/thread-863-1-1.html

主要觉得这个改了这么多天，现在不用了放我电脑有点浪费，就发出来。后面要是没用到Lua的话这个项目应该也不会继续维护。

**Comment by leasses** [comment]
> 还有: github开源的是旧版了 我这里有新版开源的源码。。 https://github.com/MikaGuraN/Index/blob/master/alua358.zip?raw=true

你还有这份源码吗？
